# Generated by Django 2.2.3 on 2020-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=50)),
                ('Second', models.CharField(max_length=50)),
                ('Third', models.CharField(max_length=50)),
                ('Fourth', models.CharField(max_length=50)),
            ],
        ),
    ]
